---
title: "QC variant pipeline"
description: |
  PCA analyses for "Target capture reveals complex origin of Vietnamese ginseng"
author:
  - name: Vincent Manzanilla 
    url: https://github.com/vincentmanz/
    affiliation: Postdoc at BaseClear/ Analyst at Data.Labs
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
editor_options: 
  markdown: 
    wrap: 200
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(ggplot2)

```

# Before filtering

## Variant quality

```{r Variant quality}

var_qual_nonF <- read.csv("./vcftools/deepvariant.cohort.lqual", sep = "\t")
colnames(var_qual_nonF) <- c("chr", "pos", "qual")
a <- ggplot(var_qual_nonF, aes(qual)) + geom_density(fill = "dodgerblue1", colour = "black", alpha = 0.3)
a + theme_light()
```

## Variant mean depth

```{r Variant mean depth}
var_depth_nonF <- read_delim("./vcftools/deepvariant.cohort.ldepth.mean", delim = "\t",
                        col_names = c("chr", "pos", "mean_depth", "var_depth_nonF"), skip = 1)
b <- ggplot(var_depth_nonF, aes(mean_depth)) + geom_density(fill = "dodgerblue1", colour = "black", alpha = 0.3)
b + theme_light() + xlim(0, 100)


#tab <- as.array(summary(var_depth_nonF$mean_depth))
#kableExtra::kable(tab) %>%
#  kableExtra::kable_styling(position = "center")

```

## Variant missingness

```{r Variant missingness}
var_miss_nonF <- read_delim("./vcftools/deepvariant.cohort.lmiss", delim = "\t",
                       col_names = c("chr", "pos", "nchr", "nfiltered", "nmiss", "fmiss"), skip = 1)

c <- ggplot(var_miss_nonF, aes(fmiss)) + geom_density(fill = "dodgerblue1", colour = "black", alpha = 0.3)
c + theme_light()

#summary(var_miss_nonF$fmiss)
```

## Minor allele frequency

```{r Minor allele frequency}

var_freq_nonF <- read_delim("./vcftools/deepvariant.cohort.frq", delim = "\t",
                       col_names = c("chr", "pos", "nalleles", "nchr", "a1", "a2"), skip = 1)
# find minor allele frequency
var_freq_nonF$maf <- var_freq_nonF %>% select(a1, a2) %>% apply(1, function(z) min(z))
d <- ggplot(var_freq_nonF, aes(maf)) + geom_density(fill = "dodgerblue1", colour = "black", alpha = 0.3)
d + theme_light()

#summary(var_freq_nonF$maf)
```

# After filtering

## Variant quality

```{r Variant quality F}
var_qual_F <- read_delim("./vcftools/vcftools/deepvariant.cohort.lqual", delim = "\t",
                       col_names = c("chr", "pos", "qual"), skip = 1)
e <- ggplot(var_qual_F, aes(qual)) + geom_density(fill = "dodgerblue1", colour = "black", alpha = 0.3)
e + theme_light()
```

## Variant mean depth

```{r Variant mean depth F}
var_depth_F <- read_delim("./vcftools/vcftools/deepvariant.cohort.ldepth.mean", delim = "\t",
                        col_names = c("chr", "pos", "mean_depth", "var_depth"), skip = 1)
f <- ggplot(var_depth_F, aes(mean_depth)) + geom_density(fill = "dodgerblue1", colour = "black", alpha = 0.3)
f + theme_light() + xlim(0, 100)
dev.off()
```

## Variant missingness F
```{r Variant missingness F}
var_miss_F <- read_delim("./vcftools/vcftools/deepvariant.cohort.lmiss", delim = "\t",
                       col_names = c("chr", "pos", "nchr", "nfiltered", "nmiss", "fmiss"), skip = 1)

g <- ggplot(var_miss_F, aes(fmiss)) + geom_density(fill = "dodgerblue1", colour = "black", alpha = 0.3)
g + theme_light()
```

## Minor allele frequency

```{r Minor allele frequency F}
var_freq_F <- read_delim("./vcftools/vcftools/deepvariant.cohort.frq", delim = "\t",
                       col_names = c("chr", "pos", "nalleles", "nchr", "a1", "a2"), skip = 1)
# find minor allele frequency
var_freq_F$maf <- var_freq_F %>% select(a1, a2) %>% apply(1, function(z) min(z))
h <- ggplot(var_freq_F, aes(maf)) + geom_density(fill = "dodgerblue1", colour = "black", alpha = 0.3)
h + theme_light()
```

# Compiled together

## Variant quality 
```{r Variant quality BA }
var_qual_F$TAG <- 'Filtered'
var_qual_nonF$TAG <- 'Non_Filtered'
df<-merge(var_qual_F,var_qual_nonF,all=TRUE)      
p<-ggplot(df, aes(x=qual, fill=TAG,color=TAG)) +
  geom_density(alpha=0.3)
p+ theme_light()+ geom_vline(xintercept = 30)
```


## Variant mean depth
```{r Variant mean depth BA  }
var_depth_F$TAG <- 'Filtered'
var_depth_nonF$TAG <- 'Non_Filtered'
df<-merge(var_depth_F,var_depth_nonF,all=TRUE)      
p<-ggplot(df, aes(x=mean_depth, fill=TAG,color=TAG)) +
  geom_density(alpha=0.3)
p + theme_light() + xlim(0, 100) + geom_vline(xintercept = 10)
```

## Variant missingness
```{r Variant missingness BA  }
var_miss_F$TAG <- 'Filtered' 
var_miss_nonF$TAG <- 'Non_Filtered'
df<-merge(var_miss_F,var_miss_nonF,all=TRUE)      
p<-ggplot(df, aes(x=fmiss, fill=TAG, color=TAG)) + geom_density(alpha=.2) 
p + theme_light() + geom_vline(xintercept = 0.20)
```

## Minor allele frequency
```{r Minor allele frequency  BA }
var_freq_F$TAG <- 'Filtered' 
var_freq_nonF$TAG <- 'Non_Filtered'
df<-merge(var_freq_F,var_freq_nonF,all=TRUE)      
p<-ggplot(df, aes(x=maf, fill=TAG, color=TAG)) + geom_density(alpha=.2) 
p + theme_light()+ geom_vline(xintercept = 0.05)
```



