./distructLinux1.1 -d drawparams_2.1_indivs
./distructLinux1.1 -d drawparams_3.1_indivs
./distructLinux1.1 -d drawparams_4.1_indivs
./distructLinux1.1 -d drawparams_5.1_indivs
./distructLinux1.1 -d drawparams_6.1_indivs
./distructLinux1.1 -d drawparams_7.1_indivs
./distructLinux1.1 -d drawparams_8.1_indivs
./distructLinux1.1 -d drawparams_9.1_indivs
./distructLinux1.1 -d drawparams_10.1_indivs
./distructLinux1.1 -d drawparams_2.1_pop
./distructLinux1.1 -d drawparams_3.1_pop
./distructLinux1.1 -d drawparams_4.1_pop
./distructLinux1.1 -d drawparams_5.1_pop
./distructLinux1.1 -d drawparams_6.1_pop
./distructLinux1.1 -d drawparams_7.1_pop
./distructLinux1.1 -d drawparams_8.1_pop
./distructLinux1.1 -d drawparams_9.1_pop
./distructLinux1.1 -d drawparams_10.1_pop